URL=https://www.asda.co.uk/
cookies=/html/body/div[2]/div[3]/div/div[1]/div/div[2]/div/button[1]

loginbtn=sign-in_btn
entername=.email-phone-input
enterpswd=password

browser1=chrome
username1= test1
password1=test1

browser2=edge
username2=test2
password2=test2

browser3=chrome
username3=
password3=test3

searchbox=//input[@class='search-input']
searchtext1=fruits
searchtext2=toys